In [2]:
dict={'key1':'abc','key2':'pqr','':'xyz'}
print (dict)

{'key1': 'abc', 'key2': 'pqr', '': 'xyz'}


In [4]:
dict['key1']

'abc'

In [0]:
dict={'k1':{'sub_k1':'sub_k1_value','sub_k2':'sub_k2_value'},'k2':'value2'}

In [6]:
print(dict)

{'k1': {'sub_k1': 'sub_k1_value', 'sub_k2': 'sub_k2_value'}, 'k2': 'value2'}


In [11]:
print(dict['k1']['sub_k1'])

sub_k1_value


In [15]:
print(dict['k1']['sub_k2'])

sub_k2_value


In [0]:
dict = {'k1':{'sub_k1' : ['sub_k1_value1','sub_k1_value2'] },  'k2':'value_outer2'}

In [20]:
print(dict['k1']['sub_k1'][1])

sub_k1_value2


In [22]:
print(dict['k1']['sub_k1'][0])

sub_k1_value1


In [25]:
print(dict['k1'],['k2'])

{'sub_k1': ['sub_k1_value1', 'sub_k1_value2']} ['k2']


In [26]:
print(dict['k2'])

value_outer2


In [27]:
print(dict)

{'k1': {'sub_k1': ['sub_k1_value1', 'sub_k1_value2']}, 'k2': 'value_outer2'}


#### list

In [30]:
name="peter"
age='38 yrs'
print('Name:',name ,' and  age:', age)

Name: peter  and  age: 38 yrs


In [31]:
print('my name is {name} and age is {age}')

my name is {name} and age is {age}


In [33]:
print('my name is {a} and my age is {b}'.format(a=name, b=age) )

my name is peter and my age is 38 yrs


### for loop

In [3]:
s=[1,2,3,4,5]
for i in s:
  print('value of i is: {} in given list'.format(i))

value of i is: 1 in given list
value of i is: 2 in given list
value of i is: 3 in given list
value of i is: 4 in given list
value of i is: 5 in given list


In [6]:
for x in range (0,10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [7]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


##list comprehension

In [0]:
x=[1,2,3,4,5]
out=[]
for num in x:
  out.append(num**2)


In [10]:
print(out)

[1, 4, 9, 16, 25]


In [11]:
print([num**2 for num in x])

[1, 4, 9, 16, 25]


In [14]:
out=[]
out=[num**3 for num in x]  
print (out)

[1, 8, 27, 64, 125]


## functions

In [0]:
def square(x):
  return x**2

In [20]:
print(square(10))

100


In [0]:
def my_func(name):
  print("My name is", name)

In [23]:
my_func('Hemant')

My name is Hemant


### function map()


In [0]:
def times_2(var):
  return var * 2

In [3]:
res=times_2(5)
print (res)

25


In [0]:
seq=[1,2,3,4,5]

### map () function is used to map with all elements of the next variable
in our example 'times_2' function is mapped with all elements of 'seq' defined above.

In [0]:
res=map(times_2,seq)

In [7]:
list(res)

[1, 4, 9, 16, 25]

### using lambda function

In [10]:
res=map(lambda num: num**2, seq)
"""
in above lamda function first occurance of 'num' is input variable and second
occurance of 'num' is return value, and this whole fucntion is applied to 'seq'
which is list defined above.
"""
print (list(res))

[1, 4, 9, 16, 25]


In [22]:
d={'k1':'abc','k2':'xyx'}
d

{'k1': 'abc', 'k2': 'xyx'}

In [23]:
for key, value in d.items():
  print(key,value)



k1 abc
k2 xyx


In [2]:
text="hi, welcome to #python"
print(text.split())

['hi,', 'welcome', 'to', '#python']


In [6]:
res=text.split('#')[1]
print(res)

python


### numpy arrays

In [0]:
test_list=[10,20,30,40,50]
import numpy as np

In [3]:
np.array(test_list)

array([10, 20, 30, 40, 50])

In [11]:
my_mat=[[10,20,30],[30,40,50],[60,70,80]]

'''
Returns list of list

'''
print(my_mat)

[[10, 20, 30], [30, 40, 50], [60, 70, 80]]


In [13]:
x=np.array(my_mat)
'''
Returns 3*3 matrix

'''
print(x)

[[10 20 30]
 [30 40 50]
 [60 70 80]]


In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

*** linspace() function prints 10 values with interval 0.5

In [22]:
np.linspace(0,5,10)  

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### np.eye() funtion is used to create identity matrix 
diagonal elements are same, rest is zero.

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(25)

array([0.39870829, 0.79220282, 0.68650087, 0.41289201, 0.81501695,
       0.02743992, 0.23022736, 0.21592118, 0.44422489, 0.96870171,
       0.17936991, 0.56492537, 0.66774113, 0.74772935, 0.18466322,
       0.28879534, 0.50342277, 0.05759305, 0.88068529, 0.56367818,
       0.17864765, 0.45945081, 0.15206864, 0.51807177, 0.77868348])

In [0]:
arr=np.arange(25)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### matrix addition using numpy array

In [0]:
mat1=np.array([[2,2,2],[3,3,3],[4,4,4]])
mat2=np.array([[5,5,5],[6,6,6],[7,7,7]])

In [0]:
for i in mat1, mat2 :
  out=mat1+mat2

In [33]:
print (out)

[[ 7  7  7]
 [ 9  9  9]
 [11 11 11]]


In [0]:
mat3=np.array([[2,2,2],[3,3,3],[4,4,4]])
mat4=np.array([[5,5,5],[6,6,6],[7,7,7]])

### matrix multiplication
wrong results

In [37]:
''' matrix multiplication with wrong output '''
print(mat3*mat4)

[[10 10 10]
 [18 18 18]
 [28 28 28]]


# Program to multiply two matrices using nested loops

In [47]:
X=np.array([[2,3,4],[5,6,7],[8,9,10]])
Y=np.array([[2,2,2],[3,3,3],[4,4,4]])
print ("X:",X)
print()
print("Y:",Y)
print()

result=np.array([[0,0,0],[0,0,0],[0,0,0]])
print("Null output:",result)


X: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Y: [[2 2 2]
 [3 3 3]
 [4 4 4]]

Null output: [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [48]:



# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

           
print("3*3 matrix multiplication output:")
for r in result:
   print(r)

3*3 matrix multiplication output:
[29 29 29]
[56 56 56]
[83 83 83]


In [52]:
''' simple way to define multidim array'''
p=np.arange(9)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
p.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Pandas ###
Series in pandas 

In [29]:
import pandas as pd
import numpy as np

list_char=['a','b','c','d','e']
list_numbers=[1,2,3,4,5]
my_dict={'name':'hemant','age':'37','address':'Mumbai'}
print(list(my_dict.items()))
print()
arr=np.random.rand(10).reshape(5,2)
print (arr)
print()
arr1=np.arange(0,20).reshape(5,4)
print(arr1)

[('name', 'hemant'), ('age', '37'), ('address', 'Mumbai')]

[[0.05566682 0.23323498]
 [0.19023201 0.82014277]
 [0.88407023 0.16186822]
 [0.13784687 0.89329259]
 [0.478898   0.65507448]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [30]:
pd.Series(data=list_numbers, index=list_char)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [31]:
pd.Series(list_char,list_numbers)

1    a
2    b
3    c
4    d
5    e
dtype: object

In [32]:
import numpy as np
import pandas as pd
from numpy.random import randn

''' random.seed() can be used to fix the randomly generated numbers
that is normally change at every repetition /// that will not let the series change everytime '''

print(np.random.seed(101))
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

None


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [14]:
type(df['W'])

pandas.core.series.Series

In [18]:
'''
The DataFrame is collection of series, thats why for 'df['W']' we are getting series as output because it is just a first column of series.
and in second command 'type(df)' we are getting actual dataframe as output.

'''
type(df)

pandas.core.frame.DataFrame

In [32]:
df['new_col']=df['W']+df['X']
df


W         X         Y         Z   new_col
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [0]:
'''
df.drop() is used to remove the particular column from the dataframe.
and axis=1 is used to refer the acutal column, axis=0 refers the row.
and 'inplace=True is used to delete the column permanantly

'''

df.drop('new_col', axis=1, inplace=True)

In [35]:
df


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
'''
similarly we can remove rows from the series,
by keeping axis=0, because when we print shape of it, we will get (5,4) where 5 is number of rows and 4 is number of columns
so when we keep axis=0 it referes to row as per the rules of array indexing
'''

df.drop('E', axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [38]:
df


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [23]:
'''
'iloc' is used to access loacation by its index.
the command given below will show the second row as a series with its index.
'''

df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [24]:
'''
'df.loc' is used to access the location by its label.
in the command  given below used 'C' label to access the desired location.
'''

df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [9]:
'''
to access specific element by its [row, col] index.
'''
df.loc['B','Y']

-0.8480769834036315

In [25]:
'''
selecting multiple rows and columns from the desired location
'''

df.loc[['A','D'],['Y','Z']]

Y         Z
A  0.907969  0.503826
D -0.933237  0.955057

In [13]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [12]:
'''
shows all cells as false that has negative value
'''

df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [27]:
'''
'booldf' is used to replace all negative values with 'NaN'
'''

booldf = df>0
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
'''
'booldf' can be replaced with the single command given below
'''

df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [19]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [20]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
'''
following command can be used to display all values except 'W'>0
'''

df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
'''
displays on that row which has  'z'<0 as a series
'''

df['Z']<0

A    False
B    False
C     True
D    False
E    False
Name: Z, dtype: bool

In [30]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
'''
shows the entire row that satisfies 'Z'<0 condition
'''

df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [34]:
print (df)
'''
to print the matrix without the above row
'''
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [5]:
'''
we can set the condition with '&' and '|' for multiple columns
'''

df[(df['X']>0) & (df['Z']>0)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [6]:
'''
we can reset the index using following fnction.
it will reset the index to numbers, instead of characters, and if we want to keep the changes permantently,
we can use 'inplace=True'
'''

df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [0]:
'''
add new column as a series in the dataframe that we are going to use as index

'''
# new_index= 'NJ','NY','CG','TK','BL'
# OR use the below line, both will give same output
new_index= 'NJ NY CG TK BL'.split()

df['CITY']=new_index

In [14]:
df

W         X         Y         Z CITY
A  2.706850  0.628133  0.907969  0.503826   NJ
B  0.651118 -0.319318 -0.848077  0.605965   NY
C -2.018168  0.740122  0.528813 -0.589001   CG
D  0.188695 -0.758872 -0.933237  0.955057   TK
E  0.190794  1.978757  2.605967  0.683509   BL

In [12]:
'''
creating new column as a series and set it as new index
'''
df.set_index('CITY')

W         X         Y         Z
CITY                                        
NJ    2.706850  0.628133  0.907969  0.503826
NY    0.651118 -0.319318 -0.848077  0.605965
CG   -2.018168  0.740122  0.528813 -0.589001
TK    0.188695 -0.758872 -0.933237  0.955057
BL    0.190794  1.978757  2.605967  0.683509

In [0]:
outer=['G1','G1','G1','G2','G2','G2']
inner=[1,2,3,4,5,6]
hier1=list(zip(outer,inner))
hier2=pd.MultiIndex.from_tuples(hier1)

In [21]:
'''
"MULTIINDEX DATAFRAME"
we are generating 6*2 random series with column 'A' and 'B'
having two groups G1 and G2 as outer index and 1 to 6 as inner index.
so that we can have subgroups G1 and G2 seperately
'''
df=pd.DataFrame(randn(6,2),hier2,['A','B'])
df

A         B
G1 1  1.025984 -0.156598
   2 -0.031579  0.649826
   3  2.154846 -0.610259
G2 4 -0.755325 -0.346419
   5  0.147027 -0.479448
   6  0.558769  1.024810

In [23]:
df.index.names=['Gropus','Numbers']
df

A         B
Gropus Numbers                    
G1     1        1.025984 -0.156598
       2       -0.031579  0.649826
       3        2.154846 -0.610259
G2     4       -0.755325 -0.346419
       5        0.147027 -0.479448
       6        0.558769  1.024810

In [27]:
# lets retreive 1.024810 from the dataframe
df.loc['G2'].loc[6]['B']


1.0248102783372157

In [30]:
df.xs(1, level='Numbers')

A         B
Gropus                    
G1      1.025984 -0.156598

In [31]:
df.xs(4, level='Numbers')

A         B
Gropus                    
G2     -0.755325 -0.346419

In [41]:
d={'k1':[1,2,np.nan],'k2':[4,np.nan,np.nan],'k3':[7,8,9]}
d

{'k1': [1, 2, nan], 'k2': [4, nan, nan], 'k3': [7, 8, 9]}

In [42]:
df=pd.DataFrame(d)
df

k1   k2  k3
0  1.0  4.0   7
1  2.0  NaN   8
2  NaN  NaN   9

In [44]:
df.dropna(axis=1)


k3
0   7
1   8
2   9

In [45]:
df.dropna(thresh=2)

k1   k2  k3
0  1.0  4.0   7
1  2.0  NaN   8

In [46]:
df

k1   k2  k3
0  1.0  4.0   7
1  2.0  NaN   8
2  NaN  NaN   9

In [48]:
df.fillna('FILLNA')

k1      k2  k3
0       1       4   7
1       2  FILLNA   8
2  FILLNA  FILLNA   9

In [49]:
df['k1'].fillna(value=df['k1'].mean())

0    1.0
1    2.0
2    1.5
Name: k1, dtype: float64

In [54]:
'''
groupby allows you to group rows together based on the column
and perform aggregate function on them

'''
data={'Company':['google','google','infosys','infosys','TCS','TCS'],
      'Name':['Sam','David','Peter','Monica','Tokyo','Nairobi'],
      'Sales':[1000,3000,1500,3000,2200,2800]}
df=pd.DataFrame(data)
df

Company     Name  Sales
0   google      Sam   1000
1   google    David   3000
2  infosys    Peter   1500
3  infosys   Monica   3000
4      TCS    Tokyo   2200
5      TCS  Nairobi   2800

In [55]:
df.groupby('Company')

In [58]:
'''
the above assignment gives dataframe object as output,
so we are following next couple of steps to get the desired ouput
'''

temp=df.groupby('Company')
temp.mean()


Sales
Company       
TCS       2500
google    2000
infosys   2250

In [59]:
temp.sum()

Sales
Company       
TCS       5000
google    4000
infosys   4500

In [60]:
temp.std()

Sales
Company             
TCS       424.264069
google   1414.213562
infosys  1060.660172

In [61]:
temp.sum().loc['TCS']

Sales    5000
Name: TCS, dtype: int64

In [62]:
df.groupby('Company').max()

Name  Sales
Company              
TCS      Tokyo   2800
google     Sam   3000
infosys  Peter   3000

In [63]:
df.groupby('Company').min()

Name  Sales
Company                
TCS      Nairobi   2200
google     David   1000
infosys   Monica   1500

In [64]:
df.groupby('Company').describe()

Sales                                                             
        count    mean          std     min     25%     50%     75%     max
Company                                                                   
TCS       2.0  2500.0   424.264069  2200.0  2350.0  2500.0  2650.0  2800.0
google    2.0  2000.0  1414.213562  1000.0  1500.0  2000.0  2500.0  3000.0
infosys   2.0  2250.0  1060.660172  1500.0  1875.0  2250.0  2625.0  3000.0

In [67]:
df.groupby('Company').describe().transpose()['google']

Sales  count       2.000000
       mean     2000.000000
       std      1414.213562
       min      1000.000000
       25%      1500.000000
       50%      2000.000000
       75%      2500.000000
       max      3000.000000
Name: google, dtype: float64

In [0]:
'''
MERGING, JOINING AND CONCATENATION
'''

df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C0','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']})

df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'C':['C4','C5','C6','C7'],
                  'D':['D4','D5','D6','D7']})

df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                  'C':['C8','C9','C10','C11'],
                  'D':['D8','D9','D10','D11']})


In [73]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [74]:
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [75]:
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [77]:
pd.concat([df1,df2,df3])

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [78]:
pd.concat([df1,df2,df3],axis=1)

A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [82]:
left=pd.DataFrame({'key':['KO','K1','K2','K3'],
                   'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3']})

right=pd.DataFrame({'key':['KO','K1','K2','K3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3']})

left


key   A   B
0  KO  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [83]:
right

key   C   D
0  KO  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [84]:
pd.merge(left,right,how='inner', on='key')

key   A   B   C   D
0  KO  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3